name: deploy
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: rajdhani

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify rajdhani-challenge about the update
        env:
          USERNAME: ${{ github.repository_owner }}
        run: |
          curl -f -X POST "https://hamr.kaustubh-dev.pipal.in/apps/$USERNAME/deploy"
          curl -f -X POST "https://capstone.kaustubh-dev.pipal.in/api/users/$USERNAME/projects/$PROJECT_NAME/checks"
