name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify rajdhani-challenge about the update
        env:
          USERNAME: ${{ github.repository_owner }}
        run: |
          curl -X POST "https://rajdhani.pipal.in/$USERNAME/deploy"
