name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wei/curl@v1
        with:
          args: -X POST https://rajdhani.pipal.in/${{ github.actor }}/deploy
